### ISSUE TITLE
Design benchmark test cases of ADAS features in LYNK&CO and VV5

### ISSUE THREAD

**Issue by XiaozhongLi** [qorosadas/ADAS#10]
Description:
Based on test cases, conduct ADAS features benchmark on LYNK&CO and VV5 to get the overall performance and functions

Expectation:
1. gather and analyze the test reports from supplier
2. generate benchmark report about function and performance
3. just get involved in test execution to enhance ADAS function

**Comment by XiaozhongLi** [comment]
Test cases available have been sent to VI.  VI will find supplier to take test execution and we will just get involved in this activity.

**Comment by minghuayao81** [comment]
Just verify all items in expectation are met, then you can drag it to 'in review'.

**Comment by XiaozhongLi** [comment]
[2018.4.16]
The test spec has been reviewed by team and sent to VI.
The latest status will be available tomorrow after communicating with VI f2f. Email was sent out.

**Comment by XiaozhongLi** [comment]
[2018.4.16]
The PR of this activity waits to be approved from Guyi's feedback. So test execution is on hold.

**Comment by XiaozhongLi** [comment]
[2018.4.17]
Its test cases are stored the link.

Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Generic\12_work products\Issues pool\#10 Design benchmark test cases of ADAS features in LYNK&CO and VV5

The following  test execution is recorded in #18
