### ISSUE TITLE
Investigate auto pull-out function 

### ISSUE THREAD

**Issue by XiaozhongLi** [qorosadas/ADAS#11]
Description:
To investigate the technology solution and market

Expectation:
1. to draft high level technology solution
2. summarize the latest technology and product in market

**Comment by XiaozhongLi** [comment]
The first draft is available now.  It need be updated based on latest information.

**Comment by minghuayao81** [comment]
whenever you are ready, please moderate a review meeting or wait for the daily meeting.

**Comment by XiaozhongLi** [comment]
[2018.4.16]
The review was finished a few days ago. But it need updating after receiving latest market news.
The above activities hasn't recorded because it happened before the tool applications.
Review meeting will be sent out when its updating will be finished.

**Comment by XiaozhongLi** [comment]
[2018.4.16]
The review was finished a few days ago. But it need updating after receiving latest market news.
The above activities hasn't been recorded because it happened before the tool applications.
Review meeting will be sent out when its updating will be finished.

**Comment by XiaozhongLi** [comment]
[2018.4.17]
The phase one investigation has been finished and reviewed. Its product is stored below link.
Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Generic\12_work products\Issues pool\#11 Investigate auto pull-out function phase one

The following phase two is planned in #17 .
