### ISSUE TITLE
Attend Beijing Auto Show 2018

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#12]
Description:
Beijing Auto Show will be opened at 25th of April to 4th of May

Expectation:
Compare all the ADAS features and generate a report

**Comment by minghuayao81** [comment]
Please consider this ticket into two parts.
The first part is for internal use, so we can get it easily solved and close this ticket.
The second part is to create a linked follow-up ticket to generate an official report for other departments.

**Comment by XiaozhongLi** [comment]
2018-5-7
The reviewed report is stored in the link: 
Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Generic\12_work products\Issues pool\#12 Attend Beijing Auto Show 2018
