### ISSUE TITLE
Prepare a training list for Nancy NIU

### ISSUE THREAD

**Issue by minghuayao81** [qorosadas/ADAS#14]
Description:
Dear all,
各位同事，
 
Since the PR process takes time, we are starting the training planning from this week. If you have any requirement for technical training, please feel free to contact me. It is highly recommended if we can have face to face discussion on this. The attachment is the training list from other OEM, just for your reference.
因为PR流程需要时间，我们从本周起开始进行培训规划。如果你有任何关于技术专业的培训，请随时与我联系。如果有时间非常期待能够与各位有机会面对面讨论。本邮件所附附件为某整车厂的配件计划，仅供参考。

Expectation:
Prepare a training list for ADAS.

**Comment by minghuayao81** [comment]
@shuangfu2020 lead this issue with support from @daileiqoros and @XiaozhongLi

**Comment by shuangfu2020** [comment]
The document is put in:
Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Generic\12_work products\Issues pool\\#14 ADAS training list collection
