### ISSUE TITLE
Prepare an ADAS feature list template for Beijing Auto Show

### ISSUE THREAD

**Issue by minghuayao81** [qorosadas/ADAS#16]
Description:
In order to better understand what ADAS our competitors have, an ADAS feature list template should be prepared.

Expectation:
- What ADAS feature does a competitor have?
- What HMI for ADAS feature, including visualization and operation?
- A template in word format should be ready before closing this ticket

**Comment by XiaozhongLi** [comment]
The template is ready to be reviewed.
