### ISSUE TITLE
Create process flow chart

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#2]
Use visio to create the process flow chart

**Comment by shuangfu2020** [comment]
@daileiqoros

**Comment by daileiqoros** [comment]
DL: have already finished the flow chart, next step we can review it internally

chart link:Qoros_share\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Generic\11_process

WIKI link: https://github.com/qorosadas/ADAS/wiki/Newbies

**Comment by daileiqoros** [comment]
write the detailed explanation for every step
