### ISSUE TITLE
Investigate "Driver Fatigue Detection" and give the performance target to VI for VTS

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#22]

**Comment by shuangfu2020** [comment]
Description:
C26 is carried over from M31T, "Driver Fatigue Detection" is an ADAS function of M31T

Expectation:
Investigate this function and give the performance target to VI for VTS

**Comment by minghuayao81** [comment]
The C26 ADAS target has been changed. The original plan is carried over from M31T, but now it changed to ADAS/PMS self-defined feature list. Therefore, the ticket here is not relevant any longer.
