### ISSUE TITLE
Make a matrix to elaborate the feature and SOP time difference for different programs

### ISSUE THREAD

**Issue by minghuayao81** [qorosadas/ADAS#23]
Description:
The investigation should include C6M0,C26 and C26L at least. If other programs also mention about ADAS, also should be relevant.

Expectation:
Make a matrix to elaborate the feature and SOP time difference for different programs.

**Comment by shuangfu2020** [comment]
The document is put in:
Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Programs feature comparison
