### ISSUE TITLE
Update Chapter 4 of ACC requirements document based on new template

### ISSUE THREAD

**Issue by XiaozhongLi** [qorosadas/ADAS#24]
Description:
ACC requirements doc need to be provided according to project development plan.

Expectation:
Update Chapter 4 in ACC requirements doc based on new template

**Comment by XiaozhongLi** [comment]
2018-5-8
The Chapter 4 of ACC will be available to be reviewed this afternoon. The meeting has been booked.

**Comment by minghuayao81** [comment]
Initial version has been delivered to PUR. DONE!
