### ISSUE TITLE
Sort out the data from Autonomous Vehicle Summit and extract the useful contents

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#28]
Description:
Sort out the data from Autonomous Vehicle Summit and extract the useful contents

Expectation:
Put all the materials in share folder, extract the useful contents and give your comments about these suppliers/technology

**Comment by minghuayao81** [comment]
If any ticket would be created because of this ticket, please put all the related tickets number in the comment.

**Comment by shuangfu2020** [comment]
All the materials are put in:
Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Training&Seminar&Conference\2nd Autonomous Driving Summit 2018
The tickets #29  and #30  are created from this ticket.
