### ISSUE TITLE
Organize a meeting with HIL testing supplier-Prescan

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#31]
Description:
Organize a meeting with HIL testing supplier, EE need to be involved together

Expectation:
Get a conclusion that which HIL solution we would have

**Comment by daileiqoros** [comment]
2018/5/11: Hirian has already came here and finished the technology review at 2018/5/9, today we received the technology material, next step expect the device list and function list

**Comment by daileiqoros** [comment]
2018/5/11: IPG came here to introduce the CarMaker SW and VIB inject device.

**Comment by daileiqoros** [comment]
2018/5/14: Prescan engineers came to Qoros to communicate the HIL technology.

**Comment by daileiqoros** [comment]
due to the Prescan HW can't do the adaptation, the HW is custom-made that based on the sensor's physical characteristic. it's not convenient for us to use HIL bench.
