### ISSUE TITLE
Define the standard of tickets

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#35]
Description:
Define the standard of tickets, discuss how to make the tickets normalization

Expectation:
Get a conclusion and follow the standard

**Comment by minghuayao81** [comment]
The decision made here anyhow should link to the board: https://github.com/qorosadas/ADAS/wiki/How-to-use-issue-tracking-tool

**Comment by minghuayao81** [comment]
I create a reference to illustrate how to create a ticket: #40 
We can modify the standard base on the template.
Colleagues can open #40 next time to do copy and paste, only need to change the content.
#40 should be automatically be closed after this ticket is done.
