### ISSUE TITLE
Investigate SAPA feasibility

### ISSUE THREAD

**Issue by minghuayao81** [qorosadas/ADAS#46]
## Description:
Investigate the feasibility of SAPA in the component meeting. Report the result in the PM meeting.

## Additional Info.:
NA

## Expectation:
- All perspectives about SAPA should be considered, including styling, sensor, ECU, actuators.
- A detailed checklist of which part is the blocker is expected.  
- The report delivered to PM meeting, both PM and PMS should be onsite.

## Checklist:
NA

**Comment by shuangfu2020** [comment]
2018/5/11:
SAPA is cancelled due to not meaningful, full-APA will be investigated for the feasibility.
