### ISSUE TITLE
Finalize DDD feature 

### ISSUE THREAD

**Issue by minghuayao81** [qorosadas/ADAS#47]
## Description:
Finalize whether DDD - Driver Drowsiness Detection is in C26 ADAS feature list.
If DDD is necessary, what DDD exactly looks like should be explained by PMS.

## Additional Info.:
NA

## Expectation:
- DDD yes or no?
- What is DDD?
- Above two questions should be answered before closing this ticket.

## Checklist:
NA

**Comment by chengzhimao** [comment]
What is DDD?
"DDD": Driver drowsiness detection.

HMI:
2 level warning on the IPC, first level contains visual warning, second level contains acoustic warning and haptic warning(option).

Technical solution:
1, mainly use "steering angle" as the algorithm input--from SAS(steering angel sensor)
Crriterion/Factors:
a) standard deviation of lane position(from SVM system or FCM)
b) distance to lane crossing(from SVM system or FCM)
c) steering angle reversal rate
d) quantity of quick steering wheel movement
2, mainly use "physiological info." of the driver as the algorithem input--from the driver monitor camera
Crriterion/Factors:
a) eyelid opening percentage
b) eye blink frequency
c) head position and toward angle
d) lie of sight direction(视线方向)
e) pupil size
f) mouth status
g) face expression
3, 1&2 fusion

details to be continou....

**Comment by shuangfu2020** [comment]
It will not be an ADAS feature in C26 project, it is an EE function totally, this info will be announced in ADAS regular meeting together with EE and PMS.
