### ISSUE TITLE
Make a timeline and deliverable list for an ADAS mule car

### ISSUE THREAD

**Issue by minghuayao81** [qorosadas/ADAS#49]
## Description:
ADAS will have a mule car standalone.
EE, CHS and ADAS(Sensors and ECU) should be ready on mule car following certain timeline and deliverables. 

## Additional Info.:
NA

## Expectation:
- Make a plan about ADAS mule car with EE, CHS and ADAS.
- On each timing defines what should be ready/deliverables.

## Checklist:
NA

**Comment by shuangfu2020** [comment]
2018/5/18:
1st version is finished and reviewed by related departments, it will be updated according to mule car built up plan from Mats.
