### ISSUE TITLE
Update Chapter 3 of ACC requirements document based on new template

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#5]
Description:
ACC requirements doc need to be provided according to project development plan.

Expectation:
Update Chapter 3 in ACC requirements doc based on new template

**Comment by XiaozhongLi** [comment]
[2018.4.16]
1. Study ACC function and radar sensor in web together with ACC spec from Intellipilot
2. investigate ADAS HIL solutions for discussion with EE

**Comment by XiaozhongLi** [comment]
[2018-4-18]
The Chapter 3 is ready to be review. The formal review will be conducted next Monday.
The peer review will be conducted tomorrow.

**Comment by XiaozhongLi** [comment]
After pre peer review, in section 4, the title is updated to sensors and one example of solution is given.
It will be reviewed by team next Monday.

**Comment by XiaozhongLi** [comment]
[2018-4-20]
The review meeting room A04 is booked 3:00 p.m. next Monday.
