### ISSUE TITLE
Attend IVC meeting

### ISSUE THREAD

**Issue by daileiqoros** [qorosadas/ADAS#51]
Description:
May 16-17,2018 2nd intelligent vehicle conference will be held at shanghai. 

Additional Info.:
NA

Expectation:
learn the knowledge of this meeting and get the materials.

Checklist:
NA

**Comment by shuangfu2020** [comment]
Already put it in:
Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Training&Seminar&Conference\Autopros_2018_IVC
