### ISSUE TITLE
LKA requirement document.

### ISSUE THREAD

**Issue by chengzhimao** [qorosadas/ADAS#56]
## Description:
Draft LKA requirements document.

## Additional Info.:
NA.

## Expectation:
Finish the LKA req. ASAP.

## Checklist:
NA

**Comment by minghuayao81** [comment]
Initial version has been delivered to PUR. DONE!

**Comment by minghuayao81** [comment]
Initial version has been delivered to PUR. DONE!

**Comment by minghuayao81** [comment]
Initial version has been delivered to PUR. DONE!
