### ISSUE TITLE
Update chapter 3 and 4.1 of  AEB requirements document 

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#6]
Description:
AEB requirements doc need to be provided according to project development plan.

Expectation:
Update AEB requirements doc based on new template, including functional diagram, detailed driving scenarios etc.

**Comment by daileiqoros** [comment]
assign to DL.

2018/4/16 DL: finished the AEB function spec: 1. driver override operation. 2 prefill operation.

**Comment by daileiqoros** [comment]
2018/4/18: update the AEB function diagram.

**Comment by daileiqoros** [comment]
2018/4/19 DL: today updated 4.1 AEB functional requirements, include ADAS-AEB-002,ADAS-AEB-003, ADAS-AEB-004,ADAS-AEB-005, ADAS-AEB-prefill.

**Comment by daileiqoros** [comment]
2018/4/20: DL: updated the ADAS-AEB-prefill;  ADAS-AEB-brake light operation,  ADAS-AEB-CNCAP requirement for AEB;

**Comment by daileiqoros** [comment]
2018/4/26 DL: after second review, needed to update the spec, 
update the function diagram.
