### ISSUE TITLE
Update TSR requirements spec based on new template

### ISSUE THREAD

**Issue by XiaozhongLi** [qorosadas/ADAS#64]
Description:

Update TSR requirements spec

Additional Info:
NA

Expectation:
Based on new template, update the requirements to v0.2

Checklist:
NA

**Comment by XiaozhongLi** [comment]
2018-5-28:
TSR v0.2 is available to be reviewed. Presently it has been sent out to team.

**Comment by minghuayao81** [comment]
Initial version has been delivered to PUR. DONE!
