### ISSUE TITLE
Ask Valeo for the APA demo car

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#73]
## Description:
Ask Wang huayang for the contact infromation of Valeo, when they can provide APA demo car for our driving

## Additional Info.:
NA

## Expectation:
Ask the bosses, sales, marketing, all related departments to try the APA demo car 

## Checklist:
NA

**Comment by daileiqoros** [comment]
2018,6,13: due to the Valeo will be checked by France government this week, so the demo car can't be sent to Qoros. and the cost is another question.

next step:discuss this problem with Valeo to find another way to show the capacity of FAPA.

**Comment by minghuayao81** [comment]
Other possible solution will be recorded in a new ticket.
