### ISSUE TITLE
APA接口和对手件性能文件编制

### ISSUE THREAD

**Issue by chengzhimao** [qorosadas/ADAS#78]
全自动泊车系统接口设计和对手件性能要求整理。

## Additional Info.:
NA

## Expectation:
完成全自动泊车的系统接口设计和对其他件的性能要求整理。主要包含ECM、ESC、EPB、EPS、TCU这些模块。

## Checklist:
NA

20180628：文件存放于——
\\10.180.10.61\Qoros_Share\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\C26\Delivery
文件名：全自动泊车系统接口需求（不含HMI） (2018)

**Comment by chengzhimao** [comment]
已经完成一份word文档，包含所有模块（不含HMI相关）的接口和性能。

**Comment by minghuayao81** [comment]
The link of such docu should be listed here.
