### ISSUE TITLE
Prepare HMI related requirements to related departments

### ISSUE THREAD

**Issue by shuangfu2020** [qorosadas/ADAS#81]
## Description:
Prepare HMI related requirements to related departments

## Additional Info.:
NA

## Expectation:
Prepare HMI related requirements to related departments, organize a meeting with related persons to confirm these requirements
## Checklist:
文件存放于——\\10.180.10.61\Qoros_Share\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\C26\Delivery
文件名：
“C26 HMI  request_lixiaozhong”
“C26 ADAS HMI讨论”
“C26 ADAS HMI req. for IPC and MMC SOR”

**Comment by chengzhimao** [comment]
整理了一份表格和一份PPT。

**Comment by minghuayao81** [comment]
The link of PPT and EXCEL sheet should be listed here.
