### ISSUE TITLE
AEB和FCW功能的CAN signal定义

### ISSUE THREAD

**Issue by daileiqoros** [qorosadas/ADAS#91]
## Description:
整理AEB以及FCW功能的交互报文。

## Additional Info.:
NA

## Expectation:
CAN signal list spec

## Checklist:
NA

**Comment by minghuayao81** [comment]
The CAN signal list spec location should be listed here.

**Comment by XiaozhongLi** [comment]
2018-6-28：
The task is finished in #97 .

Its output is in the site: Q:\PRD_DEV\Vehicle Engineering-AD\Vehicle Engineering-ADAS\Generic\12_work products\Issues pool\#97 Generate CAN signal lists of FRM&FCM
